version: "3.0"

services:
  persistence:
    build:
      context: ./Persistence/
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    stdin_open: true
    tty: true
    container_name: persistence_service
  main:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    container_name: root_service
    depends_on:
      - persistence
    environment:
      - DISPLAY=host.docker.internal:0